[phases.setup]
nixPkgs = ["nodejs_20", "python313"]

[phases.install]
cmds = [
  "npm install",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npm start"
