[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.volumes]]
mountPath = "/app/sessions"

[[deploy.volumes]]
mountPath = "/app/uploads"

[[deploy.volumes]]
mountPath = "/app/scraped_data"
