[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Railway 限制：每个服务只能有一个 volume
# 挂载 /app/data 目录，所有持久化文件存储在其中
[[deploy.volumes]]
mountPath = "/app/data"
