# Render Blueprint - Infrastructure as Code
# 使用方法: 在 Render Dashboard 中选择 "Blueprint" 并连接此文件

services:
  # Web Service - Next.js Application
  - type: web
    name: tg-bot-web
    runtime: node
    plan: starter
    region: oregon
    buildCommand: bash render-build.sh
    startCommand: bash start.sh
    healthCheckPath: /api/auth/check-status
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tg-bot-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://tg-bot-web.onrender.com
    # Persistent storage for session files, uploads, etc.
    disk:
      name: tg-bot-storage
      mountPath: /opt/render/project/src/sessions
      sizeGB: 1

# Database - PostgreSQL
databases:
  - name: tg-bot-db
    plan: free
    databaseName: tg_bot
    user: tg_bot_user
    region: oregon
